# Generated by Django 5.2.16 on 2026-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=10)),
                ('car_tezlik', models.IntegerField()),
                ('car_jarima', models.IntegerField()),
                ('vaqt', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': "Radar ma'lumot",
                'verbose_name_plural': "Radar ma'lumotlari",
                'db_table': 'radar',
                'managed': False,
            },
        ),
    ]
